#!/usr/bin/env bash

set -u

profile="UFSC IKEv2"

if nmcli -t -f NAME,TYPE connection show --active | grep -Fqx "${profile}:vpn"; then
  if nmcli connection down "$profile"; then
    notify-send "UFSC VPN" "Disconnected"
  else
    notify-send -u critical "UFSC VPN" "Could not disconnect"
  fi
else
  if nmcli connection up "$profile"; then
    notify-send "UFSC VPN" "Connected"
  else
    notify-send -u critical "UFSC VPN" "Connection failed"
  fi
fi
