#!/usr/bin/env bash

set -u

profile="UFSC IKEv2"

if nmcli -t -f NAME,TYPE connection show --active | grep -Fqx "${profile}:vpn"; then
  printf '{"text":"󰦝","tooltip":"UFSC VPN connected\\nClick to disconnect","class":"active"}\n'
else
  printf '{"text":"󰳌","tooltip":"UFSC VPN disconnected\\nClick to connect","class":"inactive"}\n'
fi
