#!/usr/bin/env bash

set -u

profile="UFSC IKEv2"

if nmcli -t -f NAME,TYPE connection show --active | grep -Fqx "${profile}:vpn"; then
  jq -cn \
    --arg text "󰌾" \
    --arg tooltip "UFSC VPN connected\nClick to disconnect" \
    '{text: $text, class: "connected", tooltip: $tooltip}'
else
  jq -cn \
    --arg text "󰌿" \
    --arg tooltip "UFSC VPN disconnected\nClick to connect" \
    '{text: $text, class: "disconnected", tooltip: $tooltip}'
fi
